# Generated by Django 4.2.5 on 2023-09-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Korpuslar', 'verbose_name_plural': 'Korpus'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Qavatlar', 'verbose_name_plural': 'Qavat'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventarlar', 'verbose_name_plural': 'Inventar'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Xonalar', 'verbose_name_plural': 'Xona'},
        ),
        migrations.AlterModelOptions(
            name='roominventory',
            options={'verbose_name': 'Xonadagi inventarlar', 'verbose_name_plural': 'Xonadagi inventar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Ma`sullar', 'verbose_name_plural': 'Ma`sul'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', 'O`rtacha'), ('2', 'Bakalavr'), ('3', 'Magistr'), ('4', 'Doktor')], default='1', max_length=1, null=True, verbose_name='Ilmiy darajasi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqacha ma`lumot'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Korpus manzili'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Korpus haqida malumot'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Korpus nomi'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpus', verbose_name='Korpus'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(verbose_name='Qavat raqami'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Inventar haqida malumot'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Inventar nomi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.floor', verbose_name='Qavat'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=255, verbose_name='Xona raqami'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='count',
            field=models.IntegerField(verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Inventar nomi'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='Xona raqami'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.CharField(default='https://cdn4.iconfinder.com/data/icons/signicon-pt-1-1/100/041_-_user_profile_avatar_login_account-1024.png', max_length=255, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='Ma`sul xona'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Familiyasi'),
        ),
    ]
