# Generated by Django 4.2.7 on 2024-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinventory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='number',
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='count',
        ),
        migrations.AddField(
            model_name='employeeinventory',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Inventar raqami'),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Inventar raqami'),
        ),
    ]
