# Generated by Django 4.2.5 on 2023-09-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_corpus_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('O`rta', 'O`rta'), ('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Doktorant', 'Doktorant')], default='O`rta', max_length=255, null=True, verbose_name='Ilmiy darajasi'),
        ),
    ]
