# Generated by Django 4.2.5 on 2023-09-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_teacher_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Soni')),
                ('status', models.CharField(choices=[('Omborda', 'Omborda'), ('Ta`mir qilinmoqda', 'Ta`mir qilinmoqda'), ('Xonaga o`rnatilgan', 'Xonaga o`rnatilgan'), ('Buzilgan', 'Buzilgan')], default='Omborda', max_length=255, verbose_name='Holati')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Inventar nomi')),
            ],
            options={
                'verbose_name': 'Omborlar',
                'verbose_name_plural': 'Ombor',
            },
        ),
    ]
