# Generated by Django 4.2.5 on 2023-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('O`rta', 'O`rta'), ('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Doktorant', 'Doktorant'), ('Professor', 'Professor'), ('Akademik', 'Akademik')], default='O`rta', max_length=255, null=True, verbose_name='Ilmiy darajasi'),
        ),
    ]
