# Generated by Django 4.2.5 on 2023-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_teacher_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventories/', verbose_name='Inventar rasmi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Rasm'),
        ),
    ]
