# Generated by Django 4.2.5 on 2023-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inventory_photo_teacher_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Narxi'),
        ),
    ]
