# Generated by Django 4.2.7 on 2023-11-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roominventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='additional_expenses',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qo`shimcha xarajatlar'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Inventar nomi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('Omborda', 'Omborda'), ('Ta`mir qilinmoqda', 'Ta`mir qilinmoqda'), ('Xonaga o`rnatilgan', 'Xonaga o`rnatilgan'), ('Buzilgan', 'Buzilgan'), ('Boshqalar', 'Boshqalar')], default='Omborda', max_length=255, verbose_name='Holati'),
        ),
    ]
